### ISSUE TITLE
Cors error

### ISSUE THREAD

**Issue by dpalay** [ashwamegh/react-link-preview#12]
What's the call to the herokuapp?  I'm getting a CORS error when trying to do this from my dev environment.
`const api = 'https://lpdg.herokuapp.com/parse/link'`

**Comment by pbpraveen1988** [comment]
@ashwamegh I am also getting the same CORS error in my production environment.

**Comment by ashwamegh** [comment]
@dpalay Hey Dave, that's the server I am using to parse the details of the link.
@dpalay @pbpraveen1988 I will check that and get back to you.

**Comment by pbpraveen1988** [comment]
@ashwamegh thanks :)

**Comment by Its-Shashank** [comment]
@ashwamegh I am also getting CORS error. Are you going to whitelist everyone's domain or how is this gonna work?
