### ISSUE TITLE
Twitter Tags?

### ISSUE THREAD

**Issue by MehadND** [ashwamegh/react-link-preview#32]
Any idea how we can use this to fetch twitter tags?

**Comment by ashwamegh** [comment]
@MehadND If there is a page for the tag, it will try to parse it, do you have any specific link to test?

**Comment by MehadND** [comment]
No just a standard twitter post url something like this (https://twitter.com/WisdenCricket/status/1752625793182630087)

I'm asking since twitter has `twitter:title` tag instead of standard `og:title`

I tried it and it didn't give me anything back from the response

**Comment by ashwamegh** [comment]
@MehadND  It will not work in that case then. It uses [`link-preview-generator`](https://github.com/AndrejGajdos/link-preview-generator), this does not have the code to parse twitter metadata.
